;;;; Misc config for better default

(tool-bar-mode -1)
(show-paren-mode 1)
(global-hl-line-mode 1)
(global-linum-mode 1)
(fset 'yes-or-no-p 'y-or-n-p)
(setq initial-scratch-message "")
(global-auto-revert-mode 1)
(require 'saveplace)
(setq-default save-place t)
(defalias 'list-buffers 'ibuffer)
(ido-mode 1)
(setq ido-separator "\n")
(setq ido-enable-flex-matching t)
(recentf-mode 1)
(setq ring-bell-function 'ignore)
;(setq browse-url-browser-function 'eww-browse-url)
(setq backup-directory-alist (quote (("." . "~/.backups"))))
(add-hook 'org-mode-hook (lambda () (setq truncate-lines nil)))
