(require-or-install 'smartparens)
(require 'smartparens-config)
(smartparens-global-mode)

(global-set-key (kbd "<f8>") 'smartparens-strict-mode)
(sp-use-paredit-bindings)
(define-key smartparens-mode-map (kbd "M-)") (lambda () (interactive) (sp-rewrap-sexp '("(" . ")"))))
(define-key smartparens-mode-map (kbd "M-}") (lambda () (interactive) (sp-rewrap-sexp '("{" . "}"))))
(define-key smartparens-mode-map (kbd "M-]") (lambda () (interactive) (sp-rewrap-sexp '("[" . "]"))))
(define-key smartparens-mode-map (kbd "M-[") 'sp-wrap-square)
(define-key smartparens-mode-map (kbd "M-]") 'sp-wrap-curly)
(define-key smartparens-mode-map (kbd "C-M-<backspace>") 'sp-backward-kill-sexp)
(define-key smartparens-mode-map (kbd "C-M-t") 'sp-transpose-sexp)
(define-key smartparens-mode-map (kbd "C-M-k") 'sp-kill-sexp)
(define-key smartparens-mode-map (kbd "C-M-w") 'sp-copy-sexp)
(define-key smartparens-mode-map (kbd "C-M-SPC") 'sp-mark-sexp)

(define-key smartparens-mode-map (kbd "M-F") 'sp-forward-symbol)
(define-key smartparens-mode-map (kbd "M-B") 'sp-backward-symbol)
(define-key smartparens-mode-map (kbd "C-(") 'sp-beginning-of-sexp)
(define-key smartparens-mode-map (kbd "C-)") 'sp-end-of-sexp)
(define-key smartparens-mode-map (kbd "C-{") 'sp-previous-sexp)
(define-key smartparens-mode-map (kbd "C-}") 'sp-next-sexp)

(define-key smartparens-mode-map (kbd "RET") 'sp-newline)
(define-key smartparens-strict-mode-map (kbd ";") 'sp-comment)
